name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v2
        with:
          ruby-version: '3.1'  # or the version specified in your Gemfile

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build

      - name: Commit and push built site
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _site
          git commit -m "Build and deploy Jekyll site"
          git push
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          publish_dir: ./_site  # default Jekyll build output directory


