name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Specify the Ruby version compatible with Jekyll
        bundler-cache: true

    - name: Install Jekyll and Bundler
      run: |
        gem install jekyll bundler

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build

    - name: Commit and push built site
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add _site
        git commit -m "Build and deploy Jekyll site"
        git push

    - name: Deploy to GitHub Pages (optional)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.MY_TOKEN }}
        publish_dir: ./_site
